version: '3'

services:
  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/home/node/app
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tracking_system
      MYSQL_USER: jonathan
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis:7.0.8-alpine
    ports:
    - "6379:6379"

volumes:
  db_data: