name: Deploy NestJS Services to Google Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy-routes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Configura a versão do Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
  
    - name: List directories
      run: ls -la

    # Instala as dependências e executa o build
    - name: Install dependencies and build the project
      run: |
        cd tracking_system/nestjs
        npm install
         npm run build -- --verbose

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY_JSON }}'

    # Deploy da função Cloud Functions com o código compilado
    - name: Deploy Routes Service to Cloud Functions
      run: |
        gcloud functions deploy routes-service --entry-point api --runtime nodejs20 --trigger-http --allow-unauthenticated --region southamerica-east1 --source=tracking_system/nestjs/dist --gen2
