name: Deploy NestJS Services to Google Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy-routes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY_JSON }}'

    - name: Set Project ID
      run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    # Uso do gcloud CLI para deploy da função Cloud Functions
    - name: Deploy Routes Service to Cloud Functions
      run: |
        gcloud functions deploy routes-service --entry-point api --runtime nodejs16 --trigger-http --allow-unauthenticated --region southamerica-east1 --source=nestjs/src/routes
