name: Deploy NestJS Services to Google Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy-routes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Decode GCP Service Account Key
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      run: echo "$GCP_SA_KEY" | base64 -d > gcp-sa-key.json
    
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v0.2.0 # Use a versão específica
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_file: gcp-sa-key.json
        export_default_credentials: true
    
    - name: Deploy Routes Service to Cloud Functions
      run: |
        gcloud functions deploy routes-service --entry-point api --runtime nodejs20 --trigger-http --allow-unauthenticated --region southamerica-east1 --source=nestjs/src/routes
    - name: Debug Cloud Functions
      run: |
        gcloud functions deploy ... --verbosity=debug